{% set name = "logtalk-jupyter-kernel" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/logtalk-jupyter-kernel-{{ version }}.tar.gz
  sha256: 447f0ea0cbff66fde9723fb6be9aff270bc8386dc6d23d2936c0063323447162

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=61.0
    - pip
  run:
    - python >=3.7
    - jupyter_client
    - ipython
    - ipykernel
    - python-graphviz
    - beautifulsoup4

test:
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/LogtalkDotOrg/logtalk-jupyter-kernel
  summary: Hercutalk - A Jupyter Kernel for Logtalk
  dev_url: https://github.com/LogtalkDotOrg/logtalk-jupyter-kernel
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pmoura
