{% set name = "logtalk-jupyter-kernel" %}
{% set version = "0.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: d91e1b5ab79aa7428e08ac4b9bfca1cb456ebd9850a70a45eba9cab97a7d88eb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}
    - jupyter_client
    - ipython
    - ipykernel
    - python-graphviz
    - beautifulsoup4

test:
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/LogtalkDotOrg/logtalk-jupyter-kernel
  summary: Hercutalk - A Jupyter Kernel for Logtalk
  dev_url: https://github.com/LogtalkDotOrg/logtalk-jupyter-kernel
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pmoura
