{% set name = "logtalk-jupyter-kernel" %}
{% set version = "0.21.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: f8d9ac141d1a2c3f5fd2d953e052fe467157f68bfd5576a993516f8f96ec36a3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}
    - jupyter_client
    - ipython
    - ipykernel
    - python-graphviz
    - beautifulsoup4
    - matplotlib

test:
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/LogtalkDotOrg/logtalk-jupyter-kernel
  summary: Hercutalk - A Jupyter Kernel for Logtalk
  dev_url: https://github.com/LogtalkDotOrg/logtalk-jupyter-kernel
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pmoura
